kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: fedora-php-s2i-base-build
  namespace: fedora-php-s2i-builds
  labels:
    name: fedora-php-s2i-base-build
spec:
  output:
    to:
      kind: DockerImage
      name: 'quay.io/cuppett/fedora-php-s2i-base:32'
    pushSecret:
      name: quayio
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      from:
        kind: ImageStreamTag
        namespace: fedora-php-s2i-builds
        name: 's2i-core:latest'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/cuppett/fedora-php-s2i'
    contextDir: base
  triggers:
    - type: GitHub
      github:
        secretReference:
          name: github-trigger
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  runPolicy: Serial